## Resources

## Importing Pytorch

In [2]:
import torch

print(torch.__version__)   # Shows currently running version of Pytorch

2.10.0+cu130


## Introduction to Tensors

### Tensors are a way to represent any form of structured or unstructured data in a multidimensional numeric form



### Creating Tensors - Pytorch Tensors are created using ```torch.tensor()``` command. The argument that it takes can be of upto any dimension

In [3]:
scalar=torch.tensor(7)  # Creates a Scalar (A Rank 0 Scalar) with stored numeric value 7
scalar

tensor(7)

### Tensor Attributes

In [4]:
scalar.ndim     # Shows the Dimension of the Tensor (Also called the Rank of the Tensor)

0

In [5]:
scalar.item()   # Returns whatever argument we fed to the tensor in its previous form back

7

### Example: Creating a vector

In [9]:
vector=torch.tensor([1,2,3,6])
print(vector)
vector.ndim

tensor([1, 2, 3, 6])


1

In [ ]:
vector.shape    # Returns the shape of the Tensor (Basically length for a vector, order for a matrix, .....)

torch.Size([4])

In **PyTorch**, `ndim` and `size` both describe the **shape of a tensor**, but they represent **different aspects** of it.

Since you like precise structure and formulas, let’s break it down carefully.

---

# 1. `ndim` (Number of Dimensions)

`tensor.ndim` tells you **how many axes the tensor has**.

Mathematically, this is the **rank of the tensor**.

[
\text{ndim} = \text{number of indices required to access an element}
]

### Example

```python
import torch

x = torch.tensor([[1,2,3],
                  [4,5,6]])

print(x.ndim)
```

Output:

```
2
```

Why?

Because you need **two indices**:

[
x_{i,j}
]

So this tensor is **2-dimensional**.

---

### Interpretation

| Tensor    | Example         | ndim |
| --------- | --------------- | ---- |
| Scalar    | `tensor(5)`     | 0    |
| Vector    | `[1,2,3]`       | 1    |
| Matrix    | `[[1,2],[3,4]]` | 2    |
| 3D tensor | `shape (2,3,4)` | 3    |

So:

[
\text{ndim} = \text{length of shape}
]

---

# 2. `size` (Shape of Each Dimension)

`tensor.size()` tells you **how many elements exist along each axis**.

It returns a **tuple representing the shape**.

---

### Example

```python
x = torch.tensor([[1,2,3],
                  [4,5,6]])

print(x.size())
```

Output:

```
torch.Size([2,3])
```

Meaning:

* 2 rows
* 3 columns

So the tensor shape is:

[
2 \times 3
]

---

# 3. Relationship Between `ndim` and `size`

If

[
\text{size} = (d_1, d_2, ..., d_k)
]

then

[
\text{ndim} = k
]

Example:

```
size = (4,5,6)
```

Then

```
ndim = 3
```

---

# 4. Example With Multiple Tensors

```python
a = torch.tensor(7)
b = torch.tensor([1,2,3])
c = torch.tensor([[1,2],[3,4]])
d = torch.rand(2,3,4)
```

| Tensor | size()    | ndim |
| ------ | --------- | ---- |
| a      | `[]`      | 0    |
| b      | `[3]`     | 1    |
| c      | `[2,2]`   | 2    |
| d      | `[2,3,4]` | 3    |

---

# 5. Important Concept (Very Useful in ML)

For neural networks:

| Tensor                             | Meaning        |
| ---------------------------------- | -------------- |
| `(batch)`                          | 1D             |
| `(batch, features)`                | 2D             |
| `(batch, channels, height, width)` | 4D (CNN input) |

Example:

```python
image_batch.shape
```

might be

```
(32, 3, 224, 224)
```

So

```
ndim = 4
```

---

# 6. Another Useful Equivalent Functions

These all mean the same thing:

```
tensor.ndim
len(tensor.shape)
len(tensor.size())
```

Example:

```python
x = torch.rand(2,3,4)

x.ndim
len(x.shape)
len(x.size())
```

All return

```
3
```

---

# 7. Your Earlier Error With Scalar

You previously tried:

```python
scalar = torch.tensor(7)
```

Then:

```
scalar.size() -> torch.Size([])
scalar.ndim -> 0
```

Because a **scalar has no axes**.

So:

```
size = []
ndim = 0
```

---

✅ **One sentence summary**

```
ndim = number of axes
size = length of each axis
```


## Creating a Matrix

In [ ]:
matrix=torch.tensor([[1,4,6],
                     [3,2,8]])    # We added 2 [ here because since torch.tensor can accept only 1 positional argument, so we group multiple arguments (here these arguments are lists) into a single list
matrix

tensor([[1, 4, 6],
        [3, 2, 8]])

In [14]:
matrix.ndim

2

## Accessing element in a Tensor

### We can access any element in a Tensor wuite similar to how we access element in lists, by using the a[i] syntax, where i is the address

In [15]:
matrix[0]

tensor([1, 4, 6])

In [17]:
matrix.shape

torch.Size([2, 3])

## Defining Tensor of Higher Ranks

In [19]:
tensor=torch.tensor([[[1,2,3],
                      [4,5,7],
                      [5,2,9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 7],
         [5, 2, 9]]])

In [ ]:
tensor.ndim    # A Rank 3 Tensor

3

In [ ]:
tensor.shape      

# Vector -> Stack of scalars

# Matrix -> Stack of Vectors -> Until this level vectors 
# get stacked either rowwise or colwise, but after this 
# (from rank 3) there is no specific structure, everything (basically the stack of matrices)
# gets stored in the same way as a scalar is stored in a vector
# We can assume it to be like a single row allocation (all matrices stacked in a single row)

# Rank 3 Tensor -> Stack of Matrices (Like a 3D Array)

# Here, size indicates:
# 1 -> Total number of Matrices stacked 
# 2 -> Row count per matrix
# 3 -> Column count per matrix

torch.Size([1, 3, 3])

![alternative text](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

`torch.Size([1, 3, 3])` means the tensor has **3 dimensions**.

[
\text{shape} = (1,3,3)
]

Let's interpret it **in matrix terms** step by step.

---

# 1. Meaning of Each Axis

In general:

[
(\text{number of matrices},; \text{rows},; \text{columns})
]

So

[
(1,3,3)
]

means

* **1 matrix**
* **3 rows**
* **3 columns**

---

# 2. Matrix Representation

It is essentially a **single (3\times3) matrix**, but stored inside a **3-D tensor container**.

[
T =
\begin{bmatrix}
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\
a_{21} & a_{22} & a_{23}\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
\end{bmatrix}
]

The outer bracket corresponds to the **first dimension (size = 1)**.

---

# 3. Example in PyTorch

```python
import torch

x = torch.tensor([[
        [1,2,3],
        [4,5,6],
        [7,8,9]
]])
```

Shape:

```python
x.size()
```

Output

```
torch.Size([1,3,3])
```

---

# 4. Indexing Interpretation

To access elements:

[
x[i,j,k]
]

where

* (i) → which matrix (0 to 0)
* (j) → row
* (k) → column

Example:

```python
x[0,1,2]
```

means

row 2, column 3 of the first matrix.

---

# 5. Why ML Libraries Use This

Even if there is **one matrix**, frameworks keep the first dimension for **batching**.

Example:

| Shape      | Meaning              |
| ---------- | -------------------- |
| `(3,3)`    | single matrix        |
| `(1,3,3)`  | batch of 1 matrix    |
| `(32,3,3)` | batch of 32 matrices |

---

# 6. Visual Structure

Think of it like a **stack of matrices**:

```
dimension 0 (depth)
      ↓

[

  3×3 matrix

]

```

Since depth = **1**, there is only one matrix in the stack.

---

✅ **Simple intuition**

```
torch.Size([1,3,3])
```

= **1 matrix of size 3×3**

---

Since you're studying ML and gradients, the **next important shape intuition** is the difference between:

```
(3,)
(3,1)
(1,3)
```

These behave **very differently in matrix multiplication and gradients**, and they confuse almost everyone initially. I can break that down if you want.


In [22]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 7],
        [5, 2, 9]])

In [ ]:
tensor[1]  # Gives error since there is only 1 matrix

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [24]:
tensor1=torch.tensor([
        [[1,2,3],
         [4,5,6],
         [7,8,9]],

        [[10,11,12],
         [13,14,15],
         [16,17,18]]
])

tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

A **rank-3 tensor (3rd order tensor)** has **3 axes / indices**.

[
T_{i,j,k}
]

You need **three indices** to locate an element.

[
\text{shape} = (d_1,d_2,d_3)
]

Example:

[
(2,3,4)
]

means

* 2 blocks
* each block is a (3\times4) matrix

---

# Visual Intuition

A **rank-3 tensor is basically a stack of matrices**.

Think of it like **multiple matrices piled on top of each other**.

## Example: shape (2,3,3)

Matrix 1

[
\begin{bmatrix}
1 & 2 & 3\
4 & 5 & 6\
7 & 8 & 9
\end{bmatrix}
]

Matrix 2

[
\begin{bmatrix}
10 & 11 & 12\
13 & 14 & 15\
16 & 17 & 18
\end{bmatrix}
]

Together they form a **rank-3 tensor**

[
T =
\begin{bmatrix}
\text{Matrix}_1 \
\text{Matrix}_2
\end{bmatrix}
]

Shape

[
(2,3,3)
]

---

# PyTorch Example

```python
import torch

T = torch.tensor([
        [[1,2,3],
         [4,5,6],
         [7,8,9]],

        [[10,11,12],
         [13,14,15],
         [16,17,18]]
])
```

Shape

```python
T.size()
```

Output

```
torch.Size([2,3,3])
```

---

# Index Meaning

[
T[i,j,k]
]

* (i) → which matrix
* (j) → row
* (k) → column

Example

```
T[1,2,0]
```

means

* second matrix
* third row
* first column

value = **16**

---

# Geometric Intuition

| Tensor        | Shape   | Interpretation    |
| ------------- | ------- | ----------------- |
| Scalar        | ()      | number            |
| Vector        | (n)     | line              |
| Matrix        | (m,n)   | table             |
| Rank-3 tensor | (a,b,c) | stack of matrices |

---

# Real ML Example

Images often use rank-3 tensors.

Example image:

[
(3,224,224)
]

means

* 3 channels (RGB)
* 224 × 224 pixels

Each channel is a **matrix**.

---

# Key Mental Model

A **rank-3 tensor = cube of numbers**

```
depth
 ↑
 │  [matrix]
 │  [matrix]
 │  [matrix]
 └────────────→ rows
      ↓
    columns
```

---

If you want, I can also show something **very important for ML**:

**Why CNN inputs are usually rank-4 tensors**

[
(\text{batch}, \text{channels}, \text{height}, \text{width})
]

and why PyTorch uses **NCHW format**. This clears up a lot of tensor confusion.


In [ ]:
tensor1.shape  # -> has 2 matrices stacked

torch.Size([2, 3, 3])

In [28]:
tensor1.ndim

3

In [ ]:
tensor2=torch.tensor([
        [[1,2],
         [4,5],
         [7,8]],

        [[10,11],
         [13,14],
         [16,17]]
         ])

tensor2

tensor([[[ 1,  2],
         [ 4,  5],
         [ 7,  8]],

        [[10, 11],
         [13, 14],
         [16, 17]]])

In [34]:
tensor2.shape

torch.Size([2, 3, 2])

## Tensor Variable Naming Conventions

In [ ]:
# Usual nomenclature for declaring Tensor variables:
# 
#  NAME   Lowercase or uppercase (usually/example)
# scalar 	 Lower (a)
# vector     Lower (y)
# matrix 	 Upper (Q)
# tensor 	 Upper (X) 

#Example:

a = torch.tensor([1,2,3])           # A VECTOR: Declared with a lowercase letter a
A = torch.tensor([[1,2,3],[5,2,9]])   # A MATRIX: Declared with a uppercase letter A

## Random Tensors

### Why Random Tensors ?

### Random Tensors are important are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

### In PyTorch, we use the ```torch.randn()``` method to generate a Random Tensor of any Rank

### Usual Flow:

```Start with Random Numbers -> Look at data -> Update Random Numbers -> Look at data -> Update random Numbers -> ...```

In [37]:
# Create a Random Tensor in PyTorch

random_tensor = torch.randn(3,4)     # Generates a 3*4 (Matrix) Random Tensor.

# The Random Numbers inside the Tensor  
# from a N(0,1) distribution (also called the standard normal distribution)

random_tensor

tensor([[-0.7455,  1.0126,  0.7814, -1.4269],
        [ 1.2491,  0.3275,  1.1408,  0.3420],
        [-1.1589,  0.4954,  0.2510,  0.4443]])